__title__ = "mindsdb-streams"
__package_name__ = 'mindsdb_streams'
__version__ = '0.0.4'
__description__ = "MindsDB Streams, provide streams capabilities to mindsdb native python library"
__email__ = "jorge@mindsdb.com"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/mindsdb_streams'
__pypi__ = 'https://pypi.org/project/mindsdb_streams/'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2018- mindsdb'
