name: MindsDB Streams workflow

on:
  push:
  pull_request:
    branches:
      - stable

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Installing general dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Installing test dependencies
      run: |
        python -m pip install -r tests/requirements.txt
    - name: Running tests
      run: |
          echo "==========Running with mindsdb version==============="
          python -m pip show mindsdb
          echo "====================================================="
          python -m tests.test_streams
      env:
        CHECK_FOR_UPDATES: False
        LOGLEVEL: 'DEBUG'
