name: MindsDB Streams workflow

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push mindsdb Docker image
      uses: docker/build-push-action@v1
      with:
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"
        repository: mindsdb/mindsdb_streams
        tag_with_ref: true
        
